### ISSUE TITLE
Please don't use PreferenceManager.getDefaultSharedPreferences()

### ISSUE THREAD

**Issue by grennis** [carnivalmobile/carnival-android-sdk#1]
I ran into a nasty problem where Carnival would just stop working... Callbacks were not being invoked when I called getMessages(), for example. I eventually tracked it down to the fact that I was in some cases calling clear() on my app's default preferences object... not realizing or expecting that this would leave Carnival in a broken state: the Device object it was getting with getDevice() no longer had a device ID, so URLs were null and this was causing NullReferenceExceptions (that silently got swallowed up).

I would request to log exceptions if something bad happens when building the request, and also not to use the app default shared preferences as I won't be the only person doing this (i.e., it's common on logout to clear preferences).

By the way, what is the proper way to "logout" of carnival and reset? (Reset user ID, etc.)

Also, where should I log bugs?

**Comment by viperwarp** [comment]
Thanks for highlighting this issue, we are already looking into it. Even if the device ID gets cleared it shouldn't break it like that and such exceptions should be logged.

There's no method as such for logging out, but setting the User ID to `""` will disassociate that user with that device.

Right here is the best place to log any bugs you find.

**Comment by grennis** [comment]
Great, thanks for the fast response!

**Comment by viperwarp** [comment]
Device ID is now stored along with the rest of Carnival's data and *not* in Default Shared Preferences.

Fixed as of [v3.0.2](https://github.com/carnivalmobile/carnival-android-sdk/releases/tag/v3.0.2)
