### ISSUE TITLE
setMessagesRead does not work

### ISSUE THREAD

**Issue by grennis** [carnivalmobile/carnival-android-sdk#2]
I noticed that my call to setMessagesRead would temporarily mark the message as read, but the next time I run the app and retrieve messages, the message is still marked as unread.

When looking in the code I noticed that this method creates the `PostMessagesMarkAsReadRunnable`, but it forgets to run the job by calling `submit` on the executor queue with the job. So, nothing happens.

**Comment by grennis** [comment]
I also noticed this problem with deleteMessage

**Comment by viperwarp** [comment]
Fixed as of [v3.0.2](https://github.com/carnivalmobile/carnival-android-sdk/releases/tag/v3.0.2)

**Comment by grennis** [comment]
It works. Thanks!
