### ISSUE TITLE
No views?

### ISSUE THREAD

**Issue by ericn37** [carnivalmobile/carnival-android-sdk#4]
It seems the only thing that it does is the registration to Carnival platform + get the token.
Logcat
```
08-22 00:39:23.649 12335-12588/com.carnivalmobile.example D/Carnival: Device Registered with Carnival: 57ba90a7616565000b62b501
08-22 00:39:23.833 12335-12588/com.carnivalmobile.example W/InstanceID/Rpc: Found 10061
08-22 00:39:24.454 12335-12588/com.carnivalmobile.example D/Carnival: Device registered with GCM
```
![device-2016-08-22-135419](https://cloud.githubusercontent.com/assets/19919208/17844833/100fa822-6870-11e6-9b1c-c2d9f0d4b4ec.png)

**Comment by samjarman** [comment]
Hey @ericn37, this is intentional, this Android sample app merely is to show an integration with the SDK. 

To see a better integration, see our Stream Examples [repo](https://github.com/carnivalmobile/carnival-stream-examples) :)
